"""Initial migration

Revision ID: 11f865affa81
Revises: 
Create Date: 2024-12-02 19:01:45.971162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f865affa81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkins', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('checkins', 'subevent_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('checkins', 'checkin_time',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('checkins', 'checked_in_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('events', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leaderboard_entries', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('leaderboard_entries', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leaderboard_entries', 'points',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subevents', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subevents', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subevents', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('subevents', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leaderboard_entries', 'points',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('leaderboard_entries', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leaderboard_entries', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('checkins', 'checked_in_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('checkins', 'checkin_time',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('checkins', 'subevent_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('checkins', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
